import * as THREE from 'three';
import { OrbitControls } from '../vendor/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from '../vendor/examples/jsm/loaders/GLTFLoader.js';

const API='https://zzicsafjzmvbfrgaizot.supabase.co/functions/v1/brandmyvan-auction';
const META={1:{name:'Sponsor_01_DriverDoor',aspect:12/6.2},3:{name:'Sponsor_03_LeftCargo',aspect:30/12.5},5:{name:'Sponsor_05_RearLeft',aspect:12/10}};
const $=id=>document.getElementById(id),canvas=$('c');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color('#f4f1e8');const camera=new THREE.PerspectiveCamera(31,1,.1,2000);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=70;controls.maxDistance=300;
const root=new THREE.Group();scene.add(root);scene.add(new THREE.HemisphereLight(0xffffff,0x8a877d,1.55));const key=new THREE.DirectionalLight(0xffffff,1.8);key.position.set(90,140,110);scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,.7);fill.position.set(-100,70,-110);scene.add(fill);
const loader=new GLTFLoader(),meshes=new Map();let selected=1,spin=false,freeVisible=true,fileUrl=null;

function resize(){const w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight),pr=renderer.getPixelRatio();if(canvas.width!==Math.round(w*pr)||canvas.height!==Math.round(h*pr))renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);resize();if(spin)root.rotation.y+=.004;controls.update();renderer.render(scene,camera)}animate();
function loadGLB(url){return new Promise((resolve,reject)=>loader.load(url,resolve,undefined,reject))}
async function readPayload(){const text=(await (await fetch('./sponsor-surfaces.bms.b64',{cache:'no-store'})).text()).replace(/\s/g,'');const bin=atob(text),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const dv=new DataView(bytes.buffer);let o=0;const magic=String.fromCharCode(bytes[o++],bytes[o++],bytes[o++],bytes[o++]);if(magic!=='BMS1')throw Error('Bad sponsor surface payload');const n=bytes[o++],out=[];for(let z=0;z<n;z++){const id=bytes[o++],nx=dv.getUint16(o,true);o+=2;const ny=dv.getUint16(o,true);o+=2;const min=[dv.getFloat32(o,true),dv.getFloat32(o+4,true),dv.getFloat32(o+8,true)];o+=12;const max=[dv.getFloat32(o,true),dv.getFloat32(o+4,true),dv.getFloat32(o+8,true)];o+=12;const count=dv.getUint32(o,true);o+=4;const p=new Float32Array(count*3);for(let i=0;i<count;i++)for(let k=0;k<3;k++){const q=dv.getUint16(o,true);o+=2;p[i*3+k]=min[k]+q/65535*(max[k]-min[k])}out.push({id,nx,ny,count,p})}return out}
function guideTex(id,aspect){const W=1024,H=Math.max(320,Math.round(W/aspect)),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.strokeStyle='#b4d300';x.lineWidth=10;x.setLineDash([28,18]);x.strokeRect(18,18,W-36,H-36);x.setLineDash([]);x.fillStyle='rgba(17,17,17,.75)';x.textAlign='center';x.textBaseline='middle';x.font='900 92px Arial';x.fillText(String(id).padStart(2,'0'),W/2,H*.47);x.font='700 30px Arial';x.fillText('SPONSOR AREA',W/2,H*.68);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function mat(map){return new THREE.MeshBasicMaterial({map,transparent:true,side:THREE.DoubleSide,depthWrite:true,polygonOffset:true,polygonOffsetFactor:-4,polygonOffsetUnits:-4})}
async function buildSurfaces(){for(const z of await readPayload()){const meta=META[z.id];if(!meta)continue;const uv=new Float32Array(z.count*2);let q=0;for(let j=0;j<=z.ny;j++)for(let i=0;i<=z.nx;i++){uv[q++]=i/z.nx;uv[q++]=1-j/z.ny}const idx=[],row=z.nx+1;for(let j=0;j<z.ny;j++)for(let i=0;i<z.nx;i++){const a=j*row+i,b=a+1,c=a+row,d=c+1;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(z.p,3));g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.Mesh(g,mat(guideTex(z.id,meta.aspect)));m.name=meta.name;m.renderOrder=30;m.userData={spotId:z.id,isGuide:true};meshes.set(z.id,m);root.add(m)}}
function imgTex(src,aspect){return new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>{const W=1024,H=Math.max(320,Math.round(W/aspect)),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d'),pad=Math.round(Math.min(W,H)*.06),s=Math.min((W-pad*2)/im.width,(H-pad*2)/im.height),dw=im.width*s,dh=im.height*s;x.clearRect(0,0,W,H);x.drawImage(im,(W-dw)/2,(H-dh)/2,dw,dh);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;resolve(t)};im.onerror=()=>reject(Error('Logo image failed'));im.src=src})}
async function applyLogo(id,src){const m=meshes.get(id),meta=META[id];if(!m)return;m.material.dispose?.();m.material=mat(await imgTex(src,meta.aspect));m.userData.isGuide=false;m.visible=true}
function restore(id){const m=meshes.get(id),meta=META[id];if(!m)return;m.material.dispose?.();m.material=mat(guideTex(id,meta.aspect));m.userData.isGuide=true;m.visible=freeVisible}
async function live(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json(),names=[];for(const id of [1,3,5]){const s=(d.spots||[]).find(x=>Number(x.id)===id);if(s?.winner_logo_url){await applyLogo(id,s.winner_logo_url);names.push(`${String(id).padStart(2,'0')} ${s.winner_company||'sponsor'}`)}}$('liveStatus').textContent='Live auction connected';$('liveText').textContent=names.length?'Applied: '+names.join(' · '):'No winner logo on 01/03/05'}catch(e){$('liveStatus').textContent='Live auction unavailable';$('liveText').textContent=e.message}}
async function boot(){try{await buildSurfaces();const van=await loadGLB('../van-realistic.glb');van.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});root.add(van.scene);const box=new THREE.Box3().setFromObject(van.scene),ctr=box.getCenter(new THREE.Vector3());controls.target.copy(ctr.clone().add(new THREE.Vector3(0,4,0)));camera.position.set(150,72,125);controls.update();controls.saveState();$('status').textContent='READY · ORIGINAL VAN + 3 PREBUILT SPONSOR SURFACES';$('diag').textContent=`surface payload: 8.9 KB\nmeshes: ${meshes.size}/3\n01: ${meshes.has(1)?'OK':'MISS'}\n03: ${meshes.has(3)?'OK':'MISS'}\n05: ${meshes.has(5)?'OK':'MISS'}\nruntime raycast: NONE\nruntime decal: NONE`;await live()}catch(e){console.error(e);$('status').textContent='LOAD ERROR · '+(e.message||e);$('diag').textContent=String(e.stack||e)}}
document.querySelectorAll('.zone').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.id);document.querySelectorAll('.zone').forEach(x=>x.classList.toggle('active',x===b))});$('file').onchange=e=>{if(fileUrl)URL.revokeObjectURL(fileUrl);const f=e.target.files?.[0];fileUrl=f?URL.createObjectURL(f):null};$('apply').onclick=()=>fileUrl?applyLogo(selected,fileUrl):alert('Choose an image first.');$('restore').onclick=()=>restore(selected);$('guides').onclick=()=>{freeVisible=!freeVisible;for(const m of meshes.values())if(m.userData.isGuide)m.visible=freeVisible;$('guides').textContent=freeVisible?'HIDE FREE GUIDES':'SHOW FREE GUIDES'};$('rotate').onclick=()=>{spin=!spin;$('rotate').textContent=spin?'STOP ROTATE':'AUTO ROTATE'};$('reset').onclick=()=>{root.rotation.set(0,0,0);controls.reset()};boot();