(function(root){
 const MODEL={length:4.75,width:1.922155520079944,height:2.0613367643228018};
 const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
 const dims=r=>({w:Math.round((r.placement?.width||0)*(r.placement?.side==='rear'?MODEL.width:MODEL.length)*100),h:Math.round((r.placement?.height||0)*MODEL.height*100)});
 const production=(value,lang)=>(lang==='fr'?{waiting:'en attente',ready_to_print:'prêt à imprimer',printed:'imprimé',installed:'posé sur le van'}:{waiting:'waiting',ready_to_print:'ready to print',printed:'printed',installed:'installed on the van'})[value]||value;
 const side=(r,lang)=>lang==='fr'?(r.placement.side==='rear'?'portes arrière':r.placement.side==='left'?'côté gauche':'côté droit'):(r.placement.side==='rear'?'rear doors':r.placement.side+' side');
 function make(r,type,lang='en'){
  const d=dims(r),price=euro(r.price_eur),area=d.w+' × '+d.h+' cm';
  if(lang==='fr'){
   if(type==='accepted')return{subject:'Brand My Van — emplacement '+r.spot_id+' confirmé',body:['Bonjour '+r.company,'','Bonne nouvelle : j’ai confirmé l’emplacement '+r.spot_id+' pour votre marque sur Brand My Van.','','Détails :','• Emplacement : '+r.spot_id+', '+side(r,'fr'),'• Surface estimée : '+area,'• Durée : '+r.duration_months+' mois','• Prix : '+price,'','Prochaine étape : merci de me confirmer vos informations de facturation et de m’envoyer votre fichier final en haute définition. Les dimensions et le fichier d’impression seront validés avant fabrication.','','Bien cordialement,','Brand My Van'].join('\\n')};
   if(type==='payment')return{subject:'Brand My Van — paiement reçu pour '+r.spot_id,body:['Bonjour '+r.company,'','Je vous confirme la réception du paiement de '+price+' pour l’emplacement '+r.spot_id+' sur Brand My Van.','','État de préparation : '+production(r.production_status,'fr')+'.','Durée prévue : '+r.duration_months+' mois.','Surface estimée : '+area+'.','','Je vous tiendrai informé de la validation du fichier, de l’impression puis de la pose sur le van.','','Merci pour votre soutien,','Brand My Van'].join('\\n')};
   return{subject:'Brand My Van — votre demande pour '+r.spot_id,body:['Bonjour '+r.company,'','Merci pour votre intérêt pour Brand My Van. Je ne peux pas confirmer l’emplacement '+r.spot_id+' demandé.','','Aucun paiement n’a été enregistré pour cette demande. Si vous le souhaitez, répondez à cet e-mail et je vous proposerai un autre emplacement disponible adapté à votre marque.','','Bien cordialement,','Brand My Van'].join('\\n')};
  }
  if(type==='accepted')return{subject:'Brand My Van — spot '+r.spot_id+' confirmed',body:['Hi '+r.company,'','Good news: I have confirmed spot '+r.spot_id+' for your brand on Brand My Van.','','Details:','• Placement: '+r.spot_id+', '+side(r,'en'),'• Estimated print area: '+area,'• Campaign duration: '+r.duration_months+' months','• Price: '+price,'','Next step: please confirm your billing details and send your final high-resolution artwork. The dimensions and print file will be checked before production.','','Best regards,','Brand My Van'].join('\\n')};
  if(type==='payment')return{subject:'Brand My Van — payment received for '+r.spot_id,body:['Hi '+r.company,'','I confirm receipt of your '+price+' payment for spot '+r.spot_id+' on Brand My Van.','','Production status: '+production(r.production_status,'en')+'.','Planned campaign duration: '+r.duration_months+' months.','Estimated print area: '+area+'.','','I will keep you updated as the artwork is approved, printed and installed on the van.','','Thank you for your support,','Brand My Van'].join('\\n')};
  return{subject:'Brand My Van — your request for '+r.spot_id,body:['Hi '+r.company,'','Thank you for your interest in Brand My Van. I am unable to confirm the requested spot '+r.spot_id+'.','','No payment has been recorded for this request. If you would like, reply to this email and I will suggest another available placement that may suit your brand.','','Best regards,','Brand My Van'].join('\\n')};
 }
 function mailto(email,subject,body){return 'mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);}
 const api={make,mailto,dims};if(typeof module==='object'&&module.exports)module.exports=api;else root.BMV_EMAIL=api;
})(globalThis);
