#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'dist'/'index.html'
s=p.read_text(encoding='utf-8')
if 'id="cist-domain-context-style"' in s: raise SystemExit('domain context already applied')
css=r'''<style id="cist-domain-context-style">
.cist-domain-context{margin:12px 0 0;padding:14px 15px;border:1px solid rgba(148,163,184,.18);border-radius:14px;background:rgba(148,163,184,.045);display:none}.cist-domain-context.show{display:block}.cist-domain-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.cist-domain-title{font-size:13px;font-weight:850}.cist-domain-badge{font-size:11px;font-weight:850;padding:4px 8px;border-radius:999px;background:rgba(148,163,184,.1)}.cist-domain-badge.new{background:rgba(245,158,11,.12);color:#fbbf24}.cist-domain-badge.very-new{background:rgba(239,68,68,.12);color:#f87171}.cist-domain-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:11px}.cist-domain-item{padding:9px 10px;border-radius:10px;background:rgba(255,255,255,.025)}.cist-domain-label{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}.cist-domain-value{margin-top:3px;font-size:12px;font-weight:750;overflow:hidden;text-overflow:ellipsis}.cist-domain-warning{margin-top:10px;font-size:12px;line-height:1.45;color:#fbbf24}@media(max-width:600px){.cist-domain-grid{grid-template-columns:1fr}.cist-domain-context{padding:12px}}
</style>'''
js=r'''<script id="cist-domain-context-script">(function(){
var input=document.getElementById('url'),result=document.getElementById('result'),card=document.getElementById('result-card');if(!input||!result||!card)return;var last='';
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function linkValue(){var v=String(input.value||'').trim();if(!v)return'';try{return new URL(/^https?:\/\//i.test(v)?v:'https://'+v).hostname}catch(e){return''}}
function fmt(d){if(!d)return'Unknown';try{return new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric'}).format(new Date(d))}catch(e){return d}}
function mount(){var old=document.getElementById('cist-domain-context');if(old)return old;var box=document.createElement('div');box.id='cist-domain-context';box.className='cist-domain-context';var anchor=document.getElementById('cist-redirect-destination')||document.getElementById('universal-summary')||card;anchor.insertAdjacentElement('afterend',box);return box}
async function run(){if(result.classList.contains('hidden'))return;var host=linkValue();if(!host||host===last)return;last=host;var box=mount();try{var r=await fetch('/api/domain-context',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({domain:host})});var d=await r.json();if(!d.available){box.classList.remove('show');return}var cls=d.ageDays!=null&&d.ageDays<30?'very-new':d.ageDays!=null&&d.ageDays<180?'new':'';var age=d.ageDays==null?'Unknown':d.ageDays<2?d.ageDays+' day old':d.ageDays<365?d.ageDays+' days old':Math.floor(d.ageDays/365)+'+ years old';var warning=d.ageDays!=null&&d.ageDays<30?'<div class="cist-domain-warning"><strong>Very new domain.</strong> A recently registered domain is not automatically malicious, but it deserves extra caution when combined with login, payment, brand-lookalike or redirect warnings.</div>':'';box.innerHTML='<div class="cist-domain-head"><div class="cist-domain-title">Domain context</div><span class="cist-domain-badge '+cls+'">'+esc(d.ageLabel||'Unknown')+'</span></div><div class="cist-domain-grid"><div class="cist-domain-item"><div class="cist-domain-label">Domain</div><div class="cist-domain-value">'+esc(d.domain)+'</div></div><div class="cist-domain-item"><div class="cist-domain-label">Registered</div><div class="cist-domain-value">'+esc(fmt(d.created))+' · '+esc(age)+'</div></div><div class="cist-domain-item"><div class="cist-domain-label">Registrar</div><div class="cist-domain-value">'+esc(d.registrar||'Not provided')+'</div></div></div>'+warning;box.classList.add('show')}catch(e){box.classList.remove('show')}}
document.addEventListener('cist:result-updated',function(){setTimeout(run,0)});input.addEventListener('input',function(){last='';var b=document.getElementById('cist-domain-context');if(b)b.classList.remove('show')});
})();</script>'''
s=s.replace('</head>',css+'\n</head>',1).replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Added RDAP domain context UI')